import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "@/components/ui/toaster";

import "./globals.css";
import Link from "next/link";
import { Selector } from "./selector";
import { BlendIcon } from "lucide-react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="p-4 flex items-center gap-4 justify-between">
          <Link className='flex gap-1' href="/">
            <BlendIcon size={24} />
            <h1 className="font-medium mb-2">Coverge</h1>
          </Link>
          {/* <h1 className="text-xl mb-2 rotate-[35deg]">|</h1> */}
          {/* <Link href="/">
            <h1 className="text-xl font-medium mb-2">Explore</h1>
          </Link> */}
          <Selector />
        </header>
        <main className="max-w-2xl mx-auto p-4">{children}</main>
        <Toaster />
      </body>
    </html>
  );
}
